### ISSUE TITLE
Update notification, update command, and telemetry sharing

### ISSUE THREAD

**Issue by guzman109** [zeroxoneafour/polonium#132]
I think an auto update and the option to share telemetry would be great to help with the development polonium. Especially since I am interested in using the nightly builds. 

Does anyone think this is possible? In the meantime, is there something we can do to share logs to help with the development?

**Comment by root-hal9000** [comment]
I would be happy to share if it helps, but I suppose whether it's a matter of @zeroxoneafour  not being flooded enough as it is lol

**Comment by zeroxoneafour** [comment]
An auto update is all up to whoever packages the script. Officially this would be KDE through the KDE Store, which doesn't auto update as far as I know. I know of AUR and Nix packages, but it would be very inconvenient for me to officially recommend and subsequently maintain them.

As for telemetry, there are a few issues.
1. I personally oppose telemetry heavily unless something such as a crash or bug happens. I wouldn't want to add it into my software even if only to monitor for errors. Given the frequency of errors in this project, prompting for telemetry every time would get annoying fast as well.
2. It wouldn't be possible without an external DBus application, and given how few people use dbus-saver despite it providing actual features, I can't possibly imagine anyone putting another service on their computer solely for telemetry.
3. I don't have the time to sift through telemetry. It's not easy to look through and fix bugs by myself already, but if I was getting flooded with reports the chances of actual issues being ignored would become much higher.

The only reason I'm super active on the project right now is because of spring break (thank god). After this week, I wouldn't expect a full release of v1.0 until sometime mid-summer. Obviously, incremental updates will be semi-regular now that everything is merged and updated, but they may start to get a little farther apart. I've thought of creating an organization for the maintainence of Polonium like Bismuth's forge, but not many people seem to understand the code or create many contributions. Also, it might be even more stressful if I turn from just lead developer to a lead developer and project manager. I suppose the best case scenario in the long run is that this project gets officially supported and taken in by KDE, but right now that's a bit of a long shot.
