### ISSUE TITLE
Ending the Polonium Project

### ISSUE THREAD

**Issue by zeroxoneafour** [zeroxoneafour/polonium#195]
Just under a year ago was the last Polonium release. It's been a long time since then, and Plasma has changed drastically. I no longer find it to be a desirable desktop environment, and 6.1 has made it borderline useless with multiple monitors. I will write a separate script to fix this, but I digress.

I have moved on to using [Krohnkite](https://github.com/anametologin/krohnkite) for Plasma 6. I may contribute to it, or maybe even make a script binding it with Plasma's tiling functionality, but as of now consider the present Polonium project located at this repository dead. This shouldn't really come as a surprise at this point, but if you've been wondering here's a definitive answer.

I have removed all sponsorship links and I discourage any more support of this project in code or financially. I hope all of you will understand where I am coming from here, and I'm sorry that I couldn't tame the Plasma 6 tiling system. If someone wants to try, the reigns are fully in your hands. Such is the beauty of open source, right?

I've considered archiving the project, but I probably won't. I don't know why. Maybe just holding out hope.

Thank you all,
Vaughan

**Comment by HeitorAugustoLN** [comment]
Hi Vaughan,

First off, I just want to say that I really appreciate the work you've put into the Polonium project. It's clear that you've poured a lot of effort into it, and it's been a fantastic tool for many of us.

I completely understand your decision, especially given the changes in Plasma. However, I would hate to see this project fade away, especially since it's been so valuable for me and so many other people.

I'm interested in learning the codebase and seeing if I can contribute to keeping the project alive. Is there anything specific that you think needs immediate attention or areas where I could help out? Any guidance you could provide would be greatly appreciated.

Thank you again for everything you've done, and I hope to contribute to Polonium in a meaningful way.

**Comment by zeroxoneafour** [comment]
@HeitorAugustoLN The script generally works, at least for me. I can't really think of any large features that I have tried to implement and haven't. It's a lot of small bugs and quirks that I couldn't find workarounds for that made the script unusable for most users.

I can help explain the structure of the code and how to develop for KWin if you have any more specific questions about it. Admittingly much of the code quality isn't great, which has definitely been an issue for maintainence.

**Comment by polirritmico** [comment]
For those looking for an alternative check: https://github.com/anametologin/krohnkite

**Comment by HeitorAugustoLN** [comment]
I am currently also writing a rewrite based on Polonium from scratch, I will eventually open source it when it's done, I hope I can fix the issues polonium had

**Comment by jcrben** [comment]
@HeitorAugustoLN did you give up on that rewrite, out of curiosity?

**Comment by HeitorAugustoLN** [comment]
> [@HeitorAugustoLN](https://github.com/HeitorAugustoLN) did you give up on that rewrite, out of curiosity?

Yeah, I ended up switching to COSMIC instead. After looking into it, it seemed better, than a kwin script, so I’ve been using it ever since.

**Comment by llucax** [comment]
Hi, I'm very sad to learn this project is abandoned.

I **strongly** recommend archiving the repository, or at least adding a big red disclaimer on the README saying that this project is not currently maintained, as it is very misleading to new users otherwise.
