### ISSUE TITLE
Windows jump when changing desktops using a touchpad

### ISSUE THREAD

**Issue by farline99** [zeroxoneafour/polonium#24]
**Describe the bug**
Windows collapse and expand when changing desktops using the touchpad. Surface Pro 6, linux-surface kernel, Fedora 38, Plasma 5.27.5, latest updates.

**To Reproduce**
1. Open any two windows on first virtual desktop
2. Open any two windows on second virtual desktop
3. Try to scroll virtual desktops using KDE Touchpad gestures
4. See windows bouncing

**Expected behavior**
Static window position

**Video**
![Screencast](https://github.com/zeroxoneafour/polonium/assets/100877226/e71dcc25-2f4b-4990-8ad1-714ed74a5e9e)

**Comment by zeroxoneafour** [comment]
Unfortunately, it is not possible to change this behavior. Kwin only allows 1 tiling layout per screen, and a large amount of code in the script was written to adapt to this. Because the layout is forced to change each time you change desktops, it causes windows on invisible desktops to be arranged randomly. There is nothing I can do about this, but everything should still be usable/functional.

**Comment by farline99** [comment]
Thank you for answer. Awesome project ❤️❤️❤️

**Comment by zeroxoneafour** [comment]
I found a way to make it work sort of. Does the latest master branch improve this issue for you?

**Comment by farline99** [comment]
It is HUGE improvement. As of now windows increase their size at the bottom by a couple of pixels when switching desktops. It's not annoying at all. You are the best ❤️❤️❤️❤️❤️❤️

**Comment by zeroxoneafour** [comment]
Good to hear, closing as completed. I was aware of the issue with having extra pixels but didn't know how to fix it.

**Comment by farline99** [comment]
❤️
