### ISSUE TITLE
Feature request - all maximised layout

### ISSUE THREAD

**Issue by gebrk** [zeroxoneafour/polonium#34]
If possible, please could you consider adding an all windows maximised layout similar to the monocle layout in bismuth.

I find this layout is useful when working on a single small screen such as my laptop but switch to normal tiling layouts for some use cases or when on a larger screen.

Switching to KWin floating layout and manually maximising windows works though it is less convenient than having the tiling manager keep everything maximised.

**Comment by zeroxoneafour** [comment]
A monocle mode, if added, would be very simple and rudimentary. Keyboard shortcuts would hardly work at all, and support for most actions would be very limited. I wouldn't really call it usable. The reason this would be the case is because the shortcuts and mouse movement bindings rely on KWin and its tiles for the most part, and without tiles much of the functionality is lost.

That being said, I could add this as a feature in v0.6.0 but it wouldn't be near the level of other tiling WM monocle layouts.

**Comment by HimDek** [comment]
> A monocle mode, if added, would be very simple and rudimentary. Keyboard shortcuts would hardly work at all, and support for most actions would be very limited. I wouldn't really call it usable. The reason this would be the case is because the shortcuts and mouse movement bindings rely on KWin and its tiles for the most part, and without tiles much of the functionality is lost.
> 
> That being said, I could add this as a feature in v0.6.0 but it wouldn't be near the level of other tiling WM monocle layouts.

Well users can still use the inbuilt kwin shortcut to cycle through windows. It would be usable that way.

**Comment by gebrk** [comment]
Yes, I was expecting that most polonium features and shortcuts would not function in a maximised layout. I would mainly use shortcuts to cycle through windows or cycle on to a tiling layout.

One thing it would be useful to keep working is the ignored windows - popup windows, filtered by window or process, and manually floated windows should not be maximised.

**Comment by zeroxoneafour** [comment]
I got a very basic monocle layout working. None of the Polonium added keybinds work with it, but others like the keybinds to switch active windows in KWin should.

**Comment by gebrk** [comment]
Thank you very much, I've just tested the nightly and monocle mode works great for me.
