### ISSUE TITLE
Avoid tiling a window if the tile it would be tiled in is smaller than the minimum size of the window

### ISSUE THREAD

**Issue by Managor** [zeroxoneafour/polonium#52]
**Describe the bug**
Demonstrative video: https://youtu.be/tkYeAsXdQBI
Often windows get tiled to spots where there is no room for them. Good examples of these are OBS and System settings. By default they shouldn't be tiled when being opened and if you use shortcuts to tile it, it should try to find a tile where it can fit. Or make it so that the tile layout moves enough to fit that window. I am not sure what the correct solution is.

**To Reproduce**
1. Fill the screen with tiles
2. Open system settings or OBS

**Expected behavior**
The window should not be tiled where it doesn't fit

**Video**
https://youtu.be/tkYeAsXdQBI

**Comment by lucaspar** [comment]
I believe an intermediate behavior, quick(er) to implement, until a "smart tiling" is put in place would go something like:

1. Find minimum width and height of the new window;
2. Find the dimensions of the candidate tiling space, following the tiling mode enabled;
3. If candidate width or height is less than the minimum, float window.

Then for a future release perhaps find a larger tile or resize the windows to all windows with minimum requirements - though a solution that optimizes the space seems to me equivalent to the knapsack problem and will not always be possible, so we'll still use this float state as a fallback.

**Comment by zeroxoneafour** [comment]
This would require a large rework to the tiling system. Right now, the tiling engines are written in a very simple way that is completely oblivious to the world around them. This is fine for the most part, because KWin does handle a lot of important stuff in the API. This feature request would require quite a massive rework to the tiling engines, however. If the code gets too complex or strays a bit too far from god, I may not have this feature.

The only window I know that even has a noticable minimum size is systemsettings. I know you mentioned OBS as well. For all the internal changes required to support this, it doesn't seem like it would be a good investment of programming resources and it may lead to less maintainable code in the future.

Aside from all of this, I still don't know why you can't force disable minimum size on Wayland with KWin.

**Comment by Managor** [comment]
Is there a way for you to query the current size of a window? Tile a window, let it settle in, query its current size and then resize its tile to fit that size?

**Comment by zeroxoneafour** [comment]
I may be able to whip something up like that. This will probably be the least intrusive solution.

**Comment by zeroxoneafour** [comment]
I have something now that works most of the time sort of. Try the master build and see if it works for you
