### ISSUE TITLE
Bismuth is still alive 🤯

### ISSUE THREAD

**Issue by farline99** [zeroxoneafour/polonium#82]
Not an error or feature request. Just wanted to share some great news. One smart, kind person [fixed Bismuth](https://github.com/Bismuth-Forge/bismuth/issues/471#issuecomment-1642640577) [by adding just one question mark](https://github.com/Bismuth-Forge/bismuth/pull/490) 😄 Now windows are tiled without any problems as before. Just need to build the package from source code yourself. Until Plasma 6 is released (early '24 at best), we still have a fully functional Bismuth.

**Comment by zeroxoneafour** [comment]
Very nice! It's good that Bismuth remains an option to people who want to use it. However, I wouldn't say that the project is alive again. The last commit was made in 2022 and the maintainers have decided to step down. It'd be nice if someone made a fork and maintained it so people have the option between integrated tiling and external tiling systems.

**Comment by farline99** [comment]
> Very nice! It's good that Bismuth remains an option to people who want to use it. However, I wouldn't say that the project is alive again. The last commit was made in 2022 and the maintainers have decided to step down. It'd be nice if someone made a fork and maintained it so people have the option between integrated tiling and external tiling systems.

We can't say it is alive again. Rather, this dev raised it from dead which is very good news, because version 5.27 will be relevant for quite a long time.

**Comment by zeroxoneafour** [comment]
> We (and I'm) can't say it is alive again.

Title of issue: "Bismuth is still alive 🤯 "

I feel like this issue is misleading in quite a few ways. Besides the title, it also contributes to the idea that Polonium is directly an improvement or descendant of Bismuth, which is also untrue. Bismuth came from Krohnkite, which came from DWM afaik. Polonium was made independently and does not contain code from any of these projects. As said in the readme, Polonium is an unofficial successor to Bismuth and a descendant of, or the code came from, kwin-autotile.

Polonium has a very different style of tile management that fits more in line with the direction it appears KWin itself is taking for tiling, supercharging the built-in tiling system instead of creating a new one on top. Many people think that Polonium can drop in and replace Bismuth, which is untrue as they are under the hood completely unrelated projects. If people prefer how Polonium works, which will probably be more similar to future KWin integrated tiling than Bismuth, it provides an alternative to an operational Bismuth on 5.27.

The purpose of this issue seems to be to say "now that Bismuth is fixed, why use this project?" If that wasn't your intent, I'm sorry for accusing you, but you should also know that the GitHub issues of a closely related project isn't the best place to share news.

**Comment by farline99** [comment]
No way am I saying that people should use Bismuth again and abandon Polonium. I wanted you to know this news, maybe you would like to use Bismuth further. I wanted to deliver good news. And that's it. I realized that this is not the best place and I looked for links to the Telegram / Matrix of this project, but did not find it, so I decided to report it here. And from the beginning, "Title of issue: "Bismuth is still alive"". He is STILL alive. Not again, but still. It's clear to me that Polonium is the way forward. it is built on the right foundation. I was happy to be able to use Bismuth for a little while before the release of Plasma 6. It is obvious to me that it will be broken there. I am very grateful to you for this project. You are doing an important work. Using it when it was autotile ❤️❤️❤️

**Comment by v3ss0n** [comment]
I had moved away to QTile, gonna check it back

**Comment by CarlosEkisde** [comment]
I'm using right now Bismuth because of the fullscreen bug. But in the long term I believe Polonium is the future. When Plasma 6 arrives bismuth will need to get ported to Qt6 and face very likely some other major changes in order to continue to work. With the main developer gone this will very likely not going to happen if no one actually steps in to work on it.

**Comment by xpufx** [comment]
> Not an error or feature request. Just wanted to share some great news. One smart, kind person [fixed Bismuth](https://github.com/Bismuth-Forge/bismuth/issues/471#issuecomment-1642640577) [by adding just one question mark](https://github.com/Bismuth-Forge/bismuth/pull/490) 😄 Now windows are tiled without any problems as before. Just need to build the package from source code yourself. Until Plasma 6 is released (early '24 at best), we still have a fully functional Bismuth.

That's one of many issues bismuth currently has with the latest plasma and more issues will crop up as plasma development continues and that of bismuth doesn't. If you check jkcdarunday's fork, he/she only has one branch -master- and has only one commit ahead of bismuth. Hardly the fork we would like.

I get your enthusiasm but I think it's a bit over the top. Cheers.
